### ISSUE TITLE
Pruebas de consultas sobre Athena

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#11]
La organización requiere que sean hechas **pruebas sobre Athena** consultando el modelo de datos implementado sobre la captura en los API's con el fin de determinar y evaluar los resultados de dichas consultas y generar una evidencia como insumo para un futuro manual.

**Entregables:**
- [x] Documento descriptivo del esquema definitivo sobre el cual se realizarán las consultas de logs en Athena
- [x] Resultados de queries de prueba en Athena

**Criterios de aceptación:**
- Documento aclarando el origen de cada dato y su tipo (adjuntar DDL)
- Resultados en formato csv
- Ambos entregables publicados en GoogleDrive

**Comment by AlaskaRising** [comment]
Se realizan pruebas sobre Athena para verificar que el Script DDL y el formato usado de la tabla funcione correctamente, se realiza documento en el cual se exponen los resultados arrojados por Athena y el archivo correspondiente exportados en formato csv :smile_cat:.

-[Documento pruebas Athena](https://docs.google.com/document/d/1WN2o7n5rUW9qk_PBafBWINwF5_5_uRGF0Txfk7ySQwY/edit) 
-[Resultados csv](https://drive.google.com/file/d/1DQEwbKggIXn-5IZlBFM_yP84oOl2AqqT/view?usp=sharing)
