### ISSUE TITLE
Estrategia de Implementación de librería de auditoría en API's

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#12]
La organización requiere la definición de una **estrategia de implementación** de las prácticas de auditoría sobre los demás API's de la organización con el fin de estandarizar y fomentar su uso. La naturaleza de dicha estrategia está sujeta a criterio de @udistrital/core, quienes decidirán la **mejor forma** de fomentar y explicar (también garantizar) su **implementación y funcionamiento**.

**Comment by mariaortiz0401** [comment]
Para la implementación de la librería de auditoría, los APIs solo deberían importar en el main.go la dirección al API (github.com/udistrital/auditoria) e inicializar por medio de auditoria.InitMiddleware(); 

Sin embargo, se presenta un problema cuando las peticiones se realizan a través del MID, pues no se tiene traza del usuario. Por eso, se realizó la siguiente prueba en el API  de Titán:

1.  Se creó una clase interceptor, que utiliza las funciones de Beego para escuchar cada petición. En este interceptor se importa la clase request del paquete util_oas y se asigna la cabecera que se acaba de escuchar utilizando una función setAlgo() en request. 

![Captura de pantalla de 2019-06-14 16-25-40](https://user-images.githubusercontent.com/8922367/59538956-fd058680-8eea-11e9-84d5-200bd1c95f64.png)

2.  En el util_oas, se creó una variable global que guarde la cabecera, y sus respectivas funciones set (usada desde el interceptor) y get: 
![Captura de pantalla de 2019-06-14 16-28-22](https://user-images.githubusercontent.com/8922367/59539047-5bcb0000-8eeb-11e9-9270-94a4a5951ff9.png)

La función get se usa en las funciones getJson y sendJson (usadas por los APIs) para capturar la cabecera y ponerla en la petición HTTP:

![Captura de pantalla de 2019-06-14 16-30-11](https://user-images.githubusercontent.com/8922367/59539120-9f256e80-8eeb-11e9-944f-a3fb532c1e67.png)

Al hacer el proceso de captura de la cabecera en el mid, siempre se tiene data del usuario. A continuación se muestra un ejemplo de petición que viene a partir del mid. Se puede ver que el user-agent es Go y la información del usuario:

![Captura de pantalla de 2019-06-14 16-32-01](https://user-images.githubusercontent.com/8922367/59539233-f3305300-8eeb-11e9-936c-db25a84a5b68.png)

**Comment by AlaskaRising** [comment]
Junto con @mariaalejandra9404 se realiza documento para detallar la correcta implementación de la librería de Auditoria en las diferentes API's :smirk_cat: .

- [Documento Implementación librería](https://docs.google.com/document/d/1Xn4WMkUE6-2CQuidgy99viIHuPXJxj6mcpxGmW1Nid4/edit?usp=sharing)
