### ISSUE TITLE
Implementación de librería de auditoría en api_crud en producción

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/auditoria#16]
Se elige titan_api_crud en producción como API para probar la librería de auditoría y hacer las respectivas pruebas de seguridad

**Comment by mariaortiz0401** [comment]
Se actualiza expresión regular a:

`@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&([^\n]*)`

**Comment by AlaskaRising** [comment]
Se modifica la expresión regular para aceptar una nueva columna la cual contiene la información generada por la API auditoria desde Beego, :cactus: :

`(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&(.+?)@&([^\n]*)`

**Comment by AlaskaRising** [comment]
Se realiza correspondiente prueba de funcionamiento:

![imagen](https://user-images.githubusercontent.com/47569218/60827307-866c4980-a175-11e9-8566-754de398031c.png)

**Comment by mariaortiz0401** [comment]
Se corrió API de Titán de nuevo para tomar cambios en la librería y se tomaron los logs que se generaron y se cargaron a un archivo de prueba al bucket S3. Los logs generados se pudieron consultar desde Athena con la estructura dada. 

![Captura de pantalla de 2019-07-08 12-21-51](https://user-images.githubusercontent.com/8922367/60829669-ef1eea80-a1a4-11e9-9bf3-148ec1407960.png)

Se puede observar que se consulta de manera apropiada. Queda pendiente el paso automático de los logs de CloudWatch a bucket S3.
