### ISSUE TITLE
Generar Plan de Trabajo

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#2]
Se busca generar el plan de trabajo para las dos fases de la modernización de auditoría de la organización. El plan de trabajo debe ser **claro** y abarcar la la solución completa.

Parte del análisis realizado en la primera fase y busca tener un insumo para el control y planeación de las siguientes etapas, por lo que debe ser lo más apegado a la realidad posible.

**Comment by AlaskaRising** [comment]
El plan para la modernizacion de la auditoria se plantea en dos fases y seguira un cronograma que se trabajara en un archivo de Drive: [Plan Trabajo Auditoria](https://docs.google.com/spreadsheets/d/1X5Mlm2hKsriMa5gaCfAd_ktiRPBCxVBHfn-pQ5hRleE/edit#gid=0), en el que se busca definir que tareas de diseño y despliegue se realizaran y cuales seran sus entregables correspondientes para cada Sprint.

**Comment by faparraf** [comment]
Se solicita revisión de @corio27 para validar formato y conveniencia del **plan de trabajo**.

**Comment by corio27** [comment]
se valida cronograma
