### ISSUE TITLE
Correciones de librería y documentación por pruebas Equipo de Seguridad

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/auditoria#26]
Dado el [documento de pruebas de auditoría](https://docs.google.com/document/d/177r3Jj2QF_5DebNuyJL-zoxaonJ2EucwF2LaDW5Nr0A/edit) compartido por el equipo de seguridad, se debe realizar la revisión del mismo y las respectivas correciones.

**Comment by mariaortiz0401** [comment]
Se agrega en documento de [estrategia de implementación](https://docs.google.com/document/d/1Xn4WMkUE6-2CQuidgy99viIHuPXJxj6mcpxGmW1Nid4/edit) el flujo de autenticación y consumo de APIs que tengan implementada la auditoría, ya que no todos los flujos usados en las pruebas son válidos para los APIs trabajados en la oficina. Se consultó con Arquitectura y, por ejemplo, el escenario Escenarios #1.0 no se tiene debe tener en cuenta ya que no se envían usuario ni contraseña. El escenario 1.1 sí es válido y debe tratarse de corregir que no traiga el usuario el endpoint de WSO2.

**Comment by mariaortiz0401** [comment]
Se aclaró con Jhon el tema de los flujos y solo uno de los propuestos en las pruebas es válido. Por esto, se completa el [documento de implementación](https://docs.google.com/document/d/1Xn4WMkUE6-2CQuidgy99viIHuPXJxj6mcpxGmW1Nid4/edit) agregando el único flujo válido.

**Comment by mariaortiz0401** [comment]
También, se respondieron las dudas de Jhon en el  [documento de pruebas de auditoría](https://docs.google.com/document/d/177r3Jj2QF_5DebNuyJL-zoxaonJ2EucwF2LaDW5Nr0A/edit)

**Comment by mariaortiz0401** [comment]
Este issue se encuentra pausado debido a que no se ha obtenido nueva información por parte del equipo de Seguridad en cuanto a las correciones que se deben hacer sobre las pruebas.

**Comment by mariaortiz0401** [comment]
Se realiza corrección en api_mid de TItán para descomentar la implementación de la librería, ya que esto puede estar causando que no se vea el usuario. Se notifica cambio en  [kanban tuelap](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=32100)

**Comment by mariaortiz0401** [comment]
Se realiza reunión con @jjvargass , @corio27  y se resuelven algunos hallazgos consignados en el documento de aditoría versión 2:

- Hallazgo 2.1.1 [/ecs/titan_api_crud_prod]: Se discute sobre este hallazgo y se acuerda que el equipo de seguridad revise el flujo de auditoría desde el cliente, ya que puede pasar que desde el Jmeter no se está autenticando igual y por eso no se puede evidenciar usuario en peticiones del CRUD que provienen del MID

- Hallazgo 2.1.2 [/ecs/titan_api_crud_prod]: Se concluye que este hallazgo es a nivel desarrollo, por lo que no va a ser tenido en cuenta en auditoría

- Hallazgo 2.1.3  [/ecs/titan_api_crud_prod]: Se concluye que este hallazgo es a nivel desarrollo, por lo que no va a ser tenido en cuenta en auditoría

- Hallazgo 2.1.4 [/ecs/titan_api_crud_prod]:  Se concluye que este hallazgo es a nivel desarrollo, por lo que no va a ser tenido en cuenta en auditoría

- Hallazgo 2.2.1 [/ecs/titan_api_mid_prod]: Se concluye que este hallazgo es a nivel desarrollo, por lo que no va a ser tenido en cuenta en auditoría 

- Hallazgo 2.2.2 [/ecs/titan_api_mid_prod]: El equipo CORE revisará el servicio que parece no ser auditado a la hora de preliquidar

- Hallazgo 3.1.1 [titan_api_mid_prod]: Se concluye que este hallazgo es a nivel desarrollo, por lo que no va a ser tenido en cuenta en auditoría

Así, las tareas pendientes son:

- Revisar Hallazgo 2.1.1 por parte de equipo de seguridad - Nueva versión de documento (V3)
- Revisar Hallazgo 2.2.2 por parte de Equipo Core 
- Revisar JMETER

**Comment by mariaortiz0401** [comment]
Se realiza reunión y se decide realizar pruebas de carga sobre el servicio de WSO2 que trae la información del usuario, ya que puede estar pasando que este servicio no responda de forma adecuada al recibir una gran cantidad de peticiones. Por esto, en [kanban](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=32100) se dispone información del servicio para que sea realizada la prueba.

**Comment by mariaortiz0401** [comment]
-Se realizó implementación de librería go-cache, que no requiere cambios en WSO2 y sí en la librería.
-Se estimo un tiempo de caché de 5 minutos pero se puede modificar a más o menos tiempo, según se requiera. 
-Se solicitó despliegue de API mid y crud de Titán y se comprobó que se guardaba el usuario en las peticiones. La hora en la que se comprobó esto es la que se ve en la siguiente imagen: 
![Captura de pantalla de 2019-10-22 12-53-04](https://user-images.githubusercontent.com/8922367/67315238-aee63c80-f4f5-11e9-9acb-949e665daa63.png)

Esto deja los APIs de Titán disponibles para nuevas pruebas de la librería de auditoría.

**Comment by mariaortiz0401** [comment]
Se realiza nuevo despliegue de titan_api_mid dadas las correciones realizadas a la librería y al util_oas y se realizó revisión de logs en Cloudwatch en titan_api_crud a las 21:32 UTC. 

Se evidenció usuario en todas las peticiones realizadas por mi usuario y el usuario de Diego Castellanos, quien se encuentra haciendo pruebas también en Titán. Esto dejaría disponible todo para realizar nuevas pruebas.

**Comment by faparraf** [comment]
Se han finalizado las correcciones sobre el componente y se solicita **aprobación** por parte de @jjvargass sobre este Issue

**Comment by jjvargass** [comment]
Buen día, comparto con ustedes V6 de las pruebas de auditoria.
El api_crud registró con éxito todos los logs.
En le api_mid se encontraron registros que no cumple con la definición de logs, pero al final se encuentra a transacción del servicio con toda la estructura. 
De esta manera se finalizan las pruebas, cumpliendo con la funcionalidad definida por el grupo core. 

https://docs.google.com/document/d/1t2tskv0njnJl5LXW_iIa1hySj-E1GRF8v_XuJGg7PK0/edit?usp=sharing

Carpeta de fuentes:
https://drive.google.com/drive/folders/1mcZD8bWmvVHZ4c-hRbq8D4mPX5my0_q7?usp=sharing
