### ISSUE TITLE
Análisis de estructura actual de los logs generados por WSO2

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#4]
La organización necesita el análisis de los logs generados por WSO2 actualmente con el fin de establecer la mejor forma de almacenarlos, consultarlos y conectarlos con información complementaria de ser necesario, para lo cual se solicita una inspección de dichos logs y el establecimiento de una estructura relacional (una única tabla) en formato DDL **debidamente documentado**.

Criterios de aceptación:
- Esquema de la tabla graficado
- Script DDL de creación de la tabla
- Diccionario de datos con aclaración de su origen.

**Comment by AlaskaRising** [comment]
Se realizo una [consulta de prueba](https://drive.google.com/drive/folders/1CheRizhEJI5iKnLz9uU0cxVHCHuhAgQG) para la table generada desde athena sobre logs guardados en formato Json.

**Comment by AlaskaRising** [comment]
Se agregan:

- ![Esquema de la tabla](https://github.com/udistrital/auditoria/blob/dev/Diagramas/Table_model_used_in_Athena.png)

- Documento de [Analisis Logs](https://docs.google.com/document/d/1Mueu2wrpEvju6vD_EVECIxcv5S89m9-G9CXoCadPXpo/edit)

- Especificacion de los datos

**Comment by AlaskaRising** [comment]
Respecto al commit anterior, la posible solución es cargar el archivo por la opción Apache, que permite el uso de expresiones regulares para la delimitación de los campos del archivo :)

**Comment by mariaalejandra9404** [comment]
Siguiendo con la propuesta a la posible solución, se planteó la siguiente expresión regular: 

> ([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\%]*)\% 

La anterior expresión divide el string recibido (el log) en siete grupos diferentes, correspondientes a los siete campos que manejan los logs de WSO2, permitiendo cualquier tipo de caracter e indicando como delimitar el signo @ (e ignorando los saltos de línea que traen problemas). Esta expresión se probó en un [tester de expresiones regulares](https://regex101.com/) con los siguientes logs: 

[PruebaLogs.txt](https://github.com/udistrital/auditoria/files/3225473/PruebaLogs.txt)

Al probarla allí, la expresión logra su objetivo de ignorar los diferentes formatos de texto que tenga el campo details. Sin embargo, al hacer uso de la expresión dentro de Athena, se presenta el mismo problema al encontrar un saldo de linea: 

![PruebaLogsAthena](https://user-images.githubusercontent.com/8922367/58447884-8e8f8e80-80cb-11e9-951a-6904057c5614.png)

Solo quedan bien aquellos logs que no tengan algún salto de linea. 

De esta manera, se investigó cómo poder ignorar este salto, pero al parecer Athena siempre leerá registro por registro y sabrá cuando acaba cada uno de ellos por medio de un salto de línea, como se indica en [este foro](https://community.hortonworks.com/questions/213085/how-to-create-an-hive-table-based-on-a-regex-proce.html). Así, la propuesta nueva es crear una función en Amazon que, al cargar los archivos en S3, se dispare y elimine los saltos de línea del archivo, para así aplicar la expresión regular desde Athena y que se carguen correctamente los logs en la tabla definida para ello.
