### ISSUE TITLE
Pruebas de queries sobre Athena

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#6]
El proyecto necesita que sean ejecutadas pruebas de queries sobre Athena para visualizar información de logs provenientes de WSO2 de una forma específica y diciente por lo que se hace imperativo generar Queries sobre la plataforma y mostrar los resultados obtenidos con el fin de validar el funcionamiento de lo desarrollado.

### Criterios de aceptación
- Resultados en formato .csv
- Query basado en casos reales

**nota**: exponer los resultados en _Google Drive_.

**Comment by mariaortiz0401** [comment]
Dado el issue #4, se crea la tabla en Athena para comenzar a probar la lectura de los logs almacenados en S3 allí. Sin embargo, dado el formato JSON de los logs, la tabla de Athena no puede leerlos correctamente y, al encontrar un salto de línea, cree que es otro registro por lo que se deforman las posibles consultas a realizar. Se indagó y se vio que en Athena se permiten varias formas de cargar los archivos desde S3, y una de ellas permite una expresión regular (Apache Web Logs), lo que permite jugar con el formato para leerlo de la mejor manera. Así, se creó la siguiente expresión regular:

Siguiendo con la propuesta a la posible solución, se planteó la siguiente expresión regular: 

> ([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\r\n]*)\@([^\%]*)\% 

La anterior expresión divide el string recibido (el log) en siete grupos diferentes, correspondientes a los siete campos que manejan los logs de WSO2, permitiendo cualquier tipo de caracter e indicando como delimitar el signo @ (e ignorando los saltos de línea que traen problemas). Esta expresión se probó en un [tester de expresiones regulares](https://regex101.com/) con los siguientes logs: 

[PruebaLogs.txt](https://github.com/udistrital/auditoria/files/3225473/PruebaLogs.txt)

Al probarla allí, la expresión logra su objetivo de ignorar los diferentes formatos de texto que tenga el campo details. Sin embargo, al hacer uso de la expresión dentro de Athena, se presenta el mismo problema al encontrar un saldo de linea: 

![PruebaLogsAthena](https://user-images.githubusercontent.com/8922367/58447884-8e8f8e80-80cb-11e9-951a-6904057c5614.png)

Solo quedan bien aquellos logs que no tengan algún salto de linea. 

De esta manera, se investigó cómo poder ignorar este salto, pero al parecer Athena siempre leerá registro por registro y sabrá cuando acaba cada uno de ellos por medio de un salto de línea, como se indica en [este foro](https://community.hortonworks.com/questions/213085/how-to-create-an-hive-table-based-on-a-regex-proce.html). Así, la propuesta nueva es crear una función en Amazon que, al cargar los archivos en S3, se dispare y elimine los saltos de línea del archivo, para así aplicar la expresión regular desde Athena y que se carguen correctamente los logs en la tabla definida para ello.

**Comment by mariaortiz0401** [comment]
De esta manera, se define que en el bucket creado para guardar los logs se creen dos carpetas: **raw_logs** y **cleaned_logs**. Se escuchará el evento de cuando se agregue un archivo cualquiera a raw_logs para que sea procesado y posteriormente guardado en la carpeta cleaned_logs para que Athena consulte esta carpeta con los logs en el formato correcto.

**Comment by mariaortiz0401** [comment]
Se probó la función, al agregar archivos al bucket de prueba, y se evidenció que se creó un nuevo archivo con el formato deseado. Se creó tabla de prueba que apuntara al bucket de prueba y se consultaron los logs: 

![PruebaSobreLogsLimpios](https://user-images.githubusercontent.com/8922367/58514253-f1972900-8190-11e9-858f-636ee1c4202e.jpg)

Sobre este script se debe corregir: 

1. Está leyendo el primer archivo del bucket. Se consultó con Jhon y él tiene planeado subir un archivo por día. De esta manera, el script debe realizar la limpieza específicamente sobre el archivo que acaba de entrar, ya que en este momento está redundando y creando archivos limpios pero de logs que ya han sido procesados
2. Se puede parametrizar el nombre del bucket por si cambia en el futuro (dejarlo como variable de entorno)
3. El nombre del archivo de prueba es 'Ejemplo.txt'. La idea es que tenga el mismo nombre del original.

**Comment by mariaortiz0401** [comment]
Dado que hemos trabajado con algunos archivos cortos que Jhon nos ha facilitado, se realizan pruebas sobre ellos. Estos logs son los que han sido procesados por la función propuesta, al dispararse por haberlos cargado en la carpeta raw_logs Bucket S3, y son los que pueden consultarse en Athena. Los resultados de las pruebas están [aquí](https://drive.google.com/drive/u/2/folders/1aW8d59yNfz0yVjZBbK0TiEO_1FCtx_cq)
