### ISSUE TITLE
Creación de documento para socialización de consultas en Athena

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#7]
La organización requiere un documento en el cual se explique la forma de hacer consulta sobre los logs con el fin de socializarlo a los encargados y a las áreas interesadas. El documento debe abarcar la globalidad del proceso y detallar el **alcance y limitaciones** del mecanismo implementado.

Criterios de aceptación:
- Documento generado en Google Docs
- Implementar formato estándar de la Organización

**Comment by mariaortiz0401** [comment]
Se realiza primera versión de documento de socialización: https://docs.google.com/document/d/1vxlKu1VMJJzfI6WAuqz_IK1CmLCQ4-mAkokiTk3gumk/edit

**Comment by AlaskaRising** [comment]
Se finaliza [Documento de socialización manejo de Logs WSO2](https://docs.google.com/document/d/1vxlKu1VMJJzfI6WAuqz_IK1CmLCQ4-mAkokiTk3gumk/edit), para revisión se detalla el proceso desde su almacenamiento hasta su posterior consulta. :)
