### ISSUE TITLE
Modificación de la estructura de la información que lleva la traza de la auditoría

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#8]
Es necesario que la librería que captura la información para la auditoría establezca y de a conocer qué información está insertando en los logs, por lo que se hace necesario que sea **modificada** la estructura de datos que se implementa y captura dentro de la librería y que los datos que aún no han sido obtenidos sean añadidos, con el fin de no solo establecer un estándar sobre los datos a almacenar sino generar una alerta sobre los datos faltantes.

Además se espera un documento explicando de dónde vendrán los datos y la estrategia inicial para obtenerlos.

**Entregables:**
- [x] Estructura modificada con comentarios describiendo el campo
- [x] Documento de la estrategia de la obtención de los datos

**Criterios de Aceptación:**
- Cambios desplegados en la rama _default_ del repositorio
- Implementación de la librería en API asignado al grupo y desplegada en producción
- Documento de estrategia hecho en Google Docs

**Comment by AlaskaRising** [comment]
Se trabaja junto con @mariaalejandra9404  [Documento de la estrategia de la obtención de los datos](https://docs.google.com/document/d/1hpUFsf1mxOX3EBie4kBNJvU---gA2vQkyEzYFtAe1TE/edit) en el cual se especifican los campos que se usaran para construir el log y las posibles formas de asegurar su obtención. :smiley:

**Comment by mariaortiz0401** [comment]
Adjunto imagen de logs de auditoría en api de configuración en producción ![2019-06-06](https://user-images.githubusercontent.com/8922367/59060562-e9c23d80-8890-11e9-9a55-746ab59d8c1d.png)
