### ISSUE TITLE
Implementación de estrategia de obtención de información

### ISSUE THREAD

**Issue by faparraf** [udistrital/auditoria#9]
La organización requiere que la información determinada por el equipo @udistrital/core en la fase de análisis de la estrategia, sea capturada y dicha estratega implementada en términos de **completar la traza** determinada con anterioridad.

**Entregables:**
- [x] Librería modificada y publicada en rama _default_
- [x] Implementación de la librería en API del grupo

**Criterios de aceptación:**
- API seleccionado desplegado en ambiente _cloud_

**Comment by AlaskaRising** [comment]
Para completar la traza y obtener toda la información establecida en el formato del log para las API's se elige implementar la siguiente estrategia, enviar en cabecera el usuario lo que requiere:    

> Cuando un usuario se autentica a través de WSO2 en el cliente se envía una cabecera en la cual se encuentra almacenada diferentes campos que permiten identificar los permisos de un usuario y establecer una sesión con una API. Entre estos campos se encuentra el access_token, por lo que se propone incluir un campo adicional en el que se almacene el nombre de usuario directamente, para su posterior almacenamiento en el log generado por alguna API. Implementar esta solución requeriría modificaciones en los clientes, probablemente a través de un interceptor, pero evitaría la dependencia que se tendría de otra forma a la base de datos de WSO2.

Para lo que se solicito usuario de WSO2, para implementar un mediador que permita adicionar el identificador de usuario en la cabecera de los mensajes.

**Comment by mariaortiz0401** [comment]
Se realizó prueba de la librería en el API de configuración que se encuentra desplegado en preproducción y en CloudWatch pudimos ver los logs con el usuario y los 8 campos más de la petición realizada. 
![Dibujo sin título](https://user-images.githubusercontent.com/8922367/59375151-136ddf80-8d3d-11e9-8cd7-3e502b00acf4.png)
